---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/library/fedora:latest
    pre_build_image: true

provisioner:
  name: ansible
  log: true

verifier:
  name: ansible
