---
- name: Assert FQDN is not 'localhost' or 'localhost.localdomain'
  assert:
    that:
      - ansible_fqdn != "localhost"
      - ansible_fqdn != "localhost.localdomain"
    fail_msg: "Invalid FQDN: {{ ansible_fqdn }}"

- name: Assert FQDN contains a dot
  assert:
    that:
      - "'{{ ansible_fqdn }}'.count('.') >= 1"
    fail_msg: "FQDN {{ ansible_fqdn }} must contain at least one dot"

- name: Assert FQDN has no underscores
  assert:
    that:
      - "'_' not in ansible_fqdn"
    fail_msg: "FQDN {{ ansible_fqdn }} must not contain underscores"

- name: Assert FQDN is lowercase
  assert:
    that:
      - ansible_fqdn == ansible_fqdn | lower
    fail_msg: "FQDN {{ ansible_fqdn }} must be lowercase"
