---
pulp_image: quay.io/pulp/pulp:stable
pulp_ports:
  - "8080:80"
pulp_volumes:
  - /var/lib/pulp/settings:/etc/pulp:Z
  - /var/lib/pulp/pulp_storage:/var/lib/pulp:Z
  - /var/lib/pulp/pgsql:/var/lib/pgsql:Z
  - /var/lib/pulp/containers:/var/lib/containers:Z
pulp_container_name: pulp
