---
- name: Pull Apache container image
  containers.podman.podman_image:
    name: "{{ httpd_container_image }}"
    state: present

- name: Create cert directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - "{{ httpd_ssl_dir }}/certs"
    - "{{ httpd_ssl_dir }}/private"
    - "{{ httpd_conf_dir }}"
    - "{{ httpd_log_dir }}"

- name: Deploy certificates
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ httpd_ssl_dir }}/{{ item.dest }}"
    remote_src: true
    mode: "0640"
  loop:
    - src: "{{ httpd_server_ca_certificate }}"
      dest: "certs/katello-server-ca.crt"
    - src: "{{ httpd_client_ca_certificate }}"
      dest: "certs/katello-default-ca.crt"
    - src: "{{ httpd_server_certificate }}"
      dest: "certs/katello-apache.crt"
    - src: "{{ httpd_server_key }}"
      dest: "private/katello-apache.key"

- name: Configure foreman-ssl vhost
  ansible.builtin.template:
    src: foreman-ssl-vhost.conf.j2
    dest: "{{ httpd_conf_dir }}/foreman-ssl.conf"
    mode: "0644"

- name: Disable welcome page in container
  ansible.builtin.file:
    path: "{{ httpd_conf_dir }}/welcome.conf"
    state: absent

- name: Run Apache as a container
  containers.podman.podman_container:
    name: httpd
    image: "{{ httpd_container_image }}"
    state: started
    volumes:
      - "{{ httpd_ssl_dir }}:/etc/httpd/ssl"
      - "{{ httpd_conf_dir }}:/etc/httpd/conf.d"
      - "{{ httpd_log_dir }}:/usr/local/apache2/logs"
    ports:
      - "80:80"
      - "443:443"
